import "./globals.css";
import Header from "../components/header/header";
import Footer from "../components/footer/Footer";
import Banner from "../components/common/Banner";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Banner />
        {children}
        <Footer />
      </body>
    </html>
  );
}
